# Generated by Django 3.2.7 on 2021-10-05 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='photo',
        ),
    ]
